### ISSUE TITLE
onirix

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-team-project-ra#1]
[Onirix.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-team-project-ra/files/11117618/Onirix.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by CxrlosMX** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
